input:
  label: "postgres_cdc"
  postgres_cdc:
    dsn: "postgresql://me:foobar@localhost:5432/datbase?sslmode=disable"
    stream_snapshot: true
    schema: public
    tables:
      - quotes
    temporary_slot: true
    slot_name: redpanda_connect_slot
pipeline:
  processors:
    - schema_registry_encode:
        url: "http://localhost:18081"
        subject: quotes-value
    - catch:
      - log:
          message: "Processing failed due to: ${!error()}"
output:
  kafka_franz:
    seed_brokers:
      - localhost:19092
    topic: quotes

